Updated README.md file to have a working example.
lubert/node-uci-engine pull request #2
Opened 2021-03-12 19:38 UTC by YesSeri

I did this to make the example in README work.

2021-03-21 23:09 UTC, lubert requested changes
Thanks for fixing the documentation, couple of small nits

2021-03-21 23:09 UTC, lubert commented on README.md
> +const position =  { fen:"r1bqkb1r/5ppp/p2ppn2/1pn5/3NP3/1BN5/PPP2PPP/R1BQR1K1 w kq - 4 10") };
Can you remove the extra space before the bracket on this line and the next?
Also, can you add a space after `fen:`

2021-03-22 10:17 UTC, YesSeri commented
I have updated the my fork, and I think I have made a pull request. I removed a parenthesis that made the example not work, and fixed the things you mentioned. Have I made a new pull request correctly?

2021-03-22 15:59 UTC, lubert commented
> I have updated the my fork, and I think I have made a pull request. I removed a parenthesis that made the example not work, and fixed the things you mentioned. Have I made a new pull request correctly?

Yep, looks good to me

2021-03-22 15:59 UTC, lubert approved these changes

2021-03-22 15:59 UTC, merged